import { Category } from '@/types/finance'

export const CATEGORIES: Category[] = [
  'Food & Dining',
  'Transport',
  'Shopping',
  'Entertainment',
  'Health',
  'Utilities',
  'Rent',
  'Savings',
]

export const CATEGORY_MERCHANTS: Record<Category, string[]> = {
  'Food & Dining': [
    'Swiggy',
    'Zomato',
    "McDonald's",
    'Starbucks',
    'Domino\'s Pizza',
    'KFC',
    'Burger King',
    'Subway',
    'Pizza Hut',
    'Dunkin\' Donuts',
  ],
  'Transport': [
    'Uber',
    'Ola',
    'Metro',
    'Indian Railways',
    'SpiceJet',
    'IndiGo',
    'Uber Auto',
    'Rapido',
    'Meru Cabs',
    'Easy Cabs',
  ],
  'Shopping': [
    'Amazon',
    'Flipkart',
    'Myntra',
    'Ajio',
    'Nykaa',
    'Tata Cliq',
    'BigBasket',
    'Grofers',
    'Reliance Digital',
    'Croma',
  ],
  'Entertainment': [
    'Netflix',
    'Amazon Prime',
    'Disney+ Hotstar',
    'Sony Liv',
    'Voot',
    'Spotify',
    'YouTube Premium',
    'Apple Music',
    'Gaana',
    'JioSaavn',
  ],
  'Health': [
    'Apollo Pharmacy',
    'MediPlus',
    'Netmeds',
    'PharmEasy',
    'Practo',
    'Lybrate',
    'HDFC Ergo',
    'ICICI Lombard',
    'Max Bupa',
    'Star Health',
  ],
  'Utilities': [
    'Airtel',
    'Jio',
    'Vi',
    'BSNL',
    'ACT Fibernet',
    'JioFiber',
    'Tata Sky',
    'Airtel Xstream',
    'Dish TV',
    'Sun Direct',
  ],
  'Rent': [
    'Magicbricks',
    '99acres',
    'Housing.com',
    'CommonFloor',
    'NoBroker',
    'Makaan',
    'PropTiger',
    'IndiaProperty',
    'QuikrHomes',
    'Sulekha',
  ],
  'Savings': [
    'HDFC Bank',
    'ICICI Bank',
    'SBI',
    'Axis Bank',
    'Kotak Bank',
    'PNB',
    'Bank of Baroda',
    'Canara Bank',
    'Union Bank',
    'IDFC First Bank',
  ],
}

export const BUDGET_LIMITS: Record<Category, number> = {
  'Food & Dining': 8000,
  'Transport': 5000,
  'Shopping': 10000,
  'Entertainment': 3000,
  'Health': 4000,
  'Utilities': 3000,
  'Rent': 25000,
  'Savings': 15000,
}

export const CATEGORY_COLOR_MAP: Record<Category, string> = {
  'Food & Dining': '#ef4444',
  'Transport': '#f97316',
  'Shopping': '#eab308',
  'Entertainment': '#84cc16',
  'Health': '#22c55e',
  'Utilities': '#06b6d4',
  'Rent': '#3b82f6',
  'Savings': '#8b5cf6',
}
